'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Header, Footer, Button, Card, Input } from '@/components';

export default function Home() {
  const router = useRouter();
  const [tokenName, setTokenName] = useState('');

  const handleLaunchToken = () => {
    router.push('/create');
  };

  const handleViewDemo = () => {
    // Open demo modal or navigate to demo page
    router.push('/demo');
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (tokenName.trim()) {
      router.push(`/create?name=${encodeURIComponent(tokenName)}`);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 bg-gray-50 dark:bg-gray-900">
        {/* Hero Section */}
        <section className="py-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-6">
              From Idea to Viral Token in{' '}
              <span className="text-blue-600">60 Seconds</span>
            </h1>
            <p className="text-xl text-gray-600 dark:text-gray-400 mb-8 max-w-2xl mx-auto">
              AI-powered cryptocurrency token creation platform that automates design, 
              marketing, and technical aspects for your next meme coin launch.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" onClick={handleLaunchToken}>
                Launch Your Token
              </Button>
              <Button variant="outline" size="lg" onClick={handleViewDemo}>
                View Demo
              </Button>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-16 px-4 sm:px-6 lg:px-8">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">
              Everything You Need to Launch
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <Card>
                <div className="text-center">
                  <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <span className="text-blue-600 text-xl font-bold" aria-label="Artificial Intelligence">AI</span>
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    AI-Generated Assets
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Logos, memes, GIFs, and marketing content generated by AI in seconds.
                  </p>
                </div>
              </Card>
              
              <Card>
                <div className="text-center">
                  <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <span className="text-green-600 text-xl font-bold">⛓️</span>
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    Multi-Chain Support
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    Deploy on Solana, Base, Arbitrum, and other popular blockchains.
                  </p>
                </div>
              </Card>
              
              <Card>
                <div className="text-center">
                  <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                    <span className="text-purple-600 text-xl font-bold">📈</span>
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    Virality Prediction
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    AI algorithms predict and optimize your token&apos;s viral potential.
                  </p>
                </div>
              </Card>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-16 px-4 sm:px-6 lg:px-8 bg-blue-600">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl font-bold text-white mb-4">
              Ready to Launch Your Token?
            </h2>
            <p className="text-blue-100 mb-8 text-lg">
              Join thousands of creators who have already launched successful tokens with DeGenie.
            </p>
            <div className="max-w-md mx-auto">
              <form onSubmit={handleFormSubmit}>
                <div className="flex gap-4">
                  <Input 
                    placeholder="Enter your token name"
                    className="flex-1"
                    name="tokenName"
                    value={tokenName}
                    onChange={(e) => setTokenName(e.target.value)}
                    required
                  />
                  <Button type="submit" variant="secondary">Get Started</Button>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
}
